// Action types for our reducer
export const CALL_API = 'CALL_API';
export const SEND_API_DATA_TO_REDUCER = 'SEND_API_DATA_TO_REDUCER';
export const SEND_SHOOTINGS_DATA_TO_REDUCER = 'SEND_SHOOTINGS_DATA_TO_REDUCER';
export const GET_HOVERED_STATE_DATA = 'GET_HOVERED_STATE_DATA';
